[package]
name = "meilisearch-tasks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
chrono = "0.4.19"
heed = "0.11.0"
serde = { version = "1.0.130", features = ["derive"] }
